const routes = require('next-routes')

module.exports = routes()
.add('merchants')
.add('election')
.add('month')
.add('tender', '/tender/:unit/:id', 'tender')
.add('unit', '/unit/:unit', 'unit')
.add('units', '/units/:parent?', 'units')
.add('dates', '/dates/:year/:month', 'dates')
.add('merchant', '/merchants/:id', 'merchant')